name: Build and Deploy to Cloud Server

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        env:
          DOCS_BASE: /pomelo-admin-docs/
        run: pnpm docs:build

      # 部署到云服务器

      - name: Deploy to Cloud Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 117.72.74.72
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: '.vitepress/dist/*'
          target: /var/www/html
          strip_components: 2
          rm: true

      # 重启 Nginx (可选)
      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 117.72.74.72
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # 设置文件权限
            chmod -R 755 /var/www/html
            # 重新加载 nginx
            nginx -t && nginx -s reload
